config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts
  end
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post "/up_vote" => "votes#up_vote", as: :up_vote
    post "/down_vote" => "votes#down_vote", as: :down_vote
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :advertisements
  resources :questions
  get "about" => "welcome#about"
  get 'welcome/contact'
  get 'welcome/faq'
  post 'users/confirm' => 'users#confirm'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
      @questions = Question.all 
    end

    def show
      @question = Question.find(params[:id])
    end

    def new 
      @question = Question.new
    end

    def create
      @question = Question.new
      @question.title = params[:question][:title]
      @question.body = params[:question][:body]

      if @question.save
        flash[:notice] = "Question was saved."
        redirect_to @question
      else
        flash.now[:alert] = "There was an error saving the question. Please try again."
        render :new
      end
    end

    def edit
      @question = Question.find(params[:id])
    end

    def update
      @question = Question.find(params[:id])
      @question.title = params[:question][:title] || @question.title
      @question.body = params[:question][:body] || @question.body
      @question.resolved = params[:question][:resolved]

      if @question.save
        flash[:notice] = "Question was updated."
        redirect_to @question
      else
        flash.now[:alert] = "There was an error saving the question. Please try again."
        render :edit
      end
    end

    def destroy
      @question = Question.find(params[:id])

      if @question.destroy
        flash[:notice] = "\"#{@question.title}\" was deleted successfully."
        redirect_to questions_path
      else
        flash.now[:alert] = "There was an error deleting the question."
        render :show
      end
    end
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
<div class="row">
    <div class="col-md-4">
        <p>Guidelines for questions</p>
        <ul>
            <li>Don't be an ass</li>
            <li>No dictionary words</li>
            <li>The more hashtags, the better</li>
        </ul>
    </div>

    <div class="col-md-8">
        <%= form_for @question do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: "form-control", placeholder: "Enter post title" %>
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, class: "form-control", placeholder: "Enter post body" %>
            </div>
            <div class="form-group">
                <%=  f.submit "Save", class: "btn btn-success" %>
            </div>
        <% end %>
    </div>
</div>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<h2><%= link_to "New Question", new_question_path %></h2>
<% @questions.each do |question| %>
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <%= @questions.index(question) + 1 %> <%= link_to question.title, question %>
            </h4>
        </div>
    </div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for questions</p>
        <ul>
            <li>Don't be an ass</li>
            <li>No dictionary words</li>
            <li>The more hashtags, the better</li>
        </ul>
    </div>

    <div class="col-md-8">
        <%= form_for @question do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: "form-control", placeholder: "Enter post title" %>
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, class: "form-control", placeholder: "Enter post body" %>
            </div>
            <div class="form-group">
                <%=  f.submit "Save" %>
            </div>
        <% end %>
    </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<div class="row">
    <div class="col-md-8">
        <p><%= @question.body %></p>
    </div>
    <div class="col-md-4">
        <%= form_with model: @question do |f| %>
            <%= label_tag(:resolved, "Is this resolved?") %>
            <%= f.check_box :resolved, input_html: { checked: @question.resolved } %>
            <%= f.submit "Mark resolved" %>
        <% end %>
        <%= link_to "Edit", edit_question_path(@question), class: "btn btn-success" %>
        <%= link_to "Delete Question", @question, method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure you want to delete this question?"} %>
    </div>
</div>